# Generated by Django 3.0.5 on 2020-05-02 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('legend', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artworks')),
                ('html_embed', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'medias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Orte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('background', models.ImageField(blank=True, null=True, upload_to='orten')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'orte',
                'verbose_name_plural': 'orten',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('master_thesis_title', models.CharField(max_length=250)),
                ('master_thesis_abstract', models.TextField(blank=True, null=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('background', models.ImageField(blank=True, null=True, upload_to='zimmern')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position_x', models.IntegerField(default=100)),
                ('position_y', models.IntegerField(default=100)),
                ('overlay', models.BooleanField(default=True)),
                ('poi_image', models.ImageField(blank=True, null=True, upload_to='poi')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition.Media')),
                ('orte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition.Orte')),
            ],
            options={
                'verbose_name': 'POI',
                'verbose_name_plural': 'POI',
                'ordering': ['orte', 'name'],
            },
        ),
        migrations.AddField(
            model_name='media',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition.Student'),
        ),
    ]
