# Generated by Django 3.0.5 on 2020-05-02 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_auto_20200502_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orte',
            options={'ordering': ['name'], 'verbose_name': 'orte', 'verbose_name_plural': 'orten'},
        ),
        migrations.RemoveField(
            model_name='orte',
            name='order',
        ),
        migrations.AddField(
            model_name='orte',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_orte', to='exhibition.Orte'),
        ),
        migrations.AddField(
            model_name='orte',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_orte', to='exhibition.Orte'),
        ),
    ]
