# Generated by Django 3.0.5 on 2020-05-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0003_auto_20200502_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='orte',
            name='entrance',
            field=models.BooleanField(default=False),
        ),
    ]
