# Generated by Django 3.0.5 on 2020-05-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0004_orte_entrance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='master_thesis_abstract',
            new_name='bachelor_thesis_abstract',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='master_thesis_title',
            new_name='bachelor_thesis_title',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='website',
            new_name='personal_website',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='overlay',
        ),
        migrations.AddField(
            model_name='media',
            name='display_in_zimmer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='media',
            name='sound',
            field=models.FileField(blank=True, null=True, upload_to='artworks'),
        ),
        migrations.AddField(
            model_name='orte',
            name='animation',
            field=models.CharField(choices=[('EQUI', 'Equirectangular Picture)'), ('INFI', 'Infinite Scroll Picture)'), ('NOJS', 'Static Picture / Live Stream)')], default='EQUI', max_length=4),
        ),
        migrations.AddField(
            model_name='orte',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orte',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to='orten'),
        ),
        migrations.AddField(
            model_name='orte',
            name='html_embed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orte',
            name='js_config',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='position_h',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='poi',
            name='position_w',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='poi',
            name='position_z',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='poi',
            name='this_is_a_cat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to='zimmern'),
        ),
        migrations.AddField(
            model_name='student',
            name='kleio_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='portfolio',
            field=models.FileField(blank=True, null=True, upload_to='portfolios'),
        ),
        migrations.AddField(
            model_name='student',
            name='project_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='project_website2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
