# Generated by Django 3.0.5 on 2020-05-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0005_auto_20200508_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
