# Generated by Django 3.0.5 on 2020-06-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0006_student_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='orte',
            name='background_sound',
            field=models.FileField(blank=True, null=True, upload_to='sounds'),
        ),
        migrations.AlterField(
            model_name='orte',
            name='animation',
            field=models.CharField(choices=[('EQUI', 'Equirectangular Picture'), ('INFI', 'Infinite Scroll Picture'), ('NOJS', 'Static Picture / Live Stream')], default='EQUI', max_length=4),
        ),
    ]
