# Generated by Django 3.0.5 on 2020-06-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0007_background_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='scale',
            field=models.IntegerField(default=100),
        ),
    ]
