# Generated by Django 3.0.5 on 2020-06-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0008_poi_scale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orte',
            options={'ordering': ['order', 'name'], 'verbose_name': 'orte', 'verbose_name_plural': 'orten'},
        ),
        migrations.AddField(
            model_name='orte',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
