# Generated by Django 3.0.5 on 2020-06-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0009_add_order_orte'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='this_is_a_sound',
            field=models.BooleanField(default=False),
        ),
    ]
