# Generated by Django 3.0.5 on 2020-06-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0011_poi_hide_overlay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['order', 'name'], 'verbose_name': 'media', 'verbose_name_plural': 'medias'},
        ),
        migrations.AddField(
            model_name='media',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
