# Generated by Django 3.0.5 on 2020-06-10 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0012_add_order_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('file', models.FileField(blank=True, null=True, upload_to='files')),
                ('counter', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition.Student')),
            ],
            options={
                'verbose_name': 'tracked file',
                'verbose_name_plural': 'tracked files',
                'ordering': ['name'],
            },
        ),
    ]
