# Generated by Django 3.0.5 on 2020-06-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0014_poi_url_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='url_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
