# Generated by Django 3.0.5 on 2020-06-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0015_poi_url_no_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='css_class',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
