# Generated by Django 3.0.5 on 2020-06-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0016_poi_css_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='orte',
            name='map_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orte',
            name='map_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orte',
            name='position_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orte',
            name='position_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orte',
            name='zoom',
            field=models.IntegerField(default=1),
        ),
    ]
