# Generated by Django 3.0.5 on 2020-06-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0018_orte_hide_on_entrance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.TextField(blank=True, null=True)),
                ('display_program', models.BooleanField(default=True)),
                ('impressum', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'content management',
                'verbose_name_plural': 'contents management',
            },
        ),
    ]
