# Generated by Django 3.0.5 on 2020-06-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0019_contentmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='orte',
            name='position_z',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
