# Generated by Django 3.0.5 on 2020-06-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0020_orte_position_z'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='this_specific_class_endless',
            field=models.BooleanField(default=False),
        ),
    ]
