# Generated by Django 3.0.5 on 2020-06-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0021_poi_this_specific_class_endless'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='this_fullscreen_video',
            field=models.BooleanField(default=False),
        ),
    ]
