# Generated by Django 3.0.5 on 2020-06-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0022_poi_this_fullscreen_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orte',
            name='zoom',
            field=models.FloatField(default=1),
        ),
    ]
