# Generated by Django 3.0.5 on 2020-06-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0023_poi_zoom_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='orten',
            field=models.ManyToManyField(to='exhibition.Orte'),
        ),
    ]
